### PR TITLE
Support MOK blacklist

### PR DESCRIPTION
**Pull request by lcp**
This patch set adds the mokx support to allow the user to import the banned keys and hashes. It also includes the patches to improve the hash list to support multiple hashes in one signature list.

The related changes of mokutil is available in https://github.com/lcp/mokutil/tree/mokx-import

### CODE REVIEW

**Comment by vathpela** [comment]
I've pulled this into master, but I'm going to push a change to turn SHA-1 back off for our mok lists; we really shouldn't be encouraging its use at all.

TBH I'm a little unsure we should be keeping 3b8cc123ce (from some time ago), but since it's just for display, there's not a major concern.

**Comment by lcp** [comment]
"openssl x509 -fingerprint" uses sha1 by default. For convenience, I switched the certificate digest from sha256 to sha1, so the user can verify the key with the digest. I would happily to use sha256 once openssl ditches sha1.

**Comment by vathpela** [comment]
Yeah, that's why I didn't make 6d4803a1c0 also stop 3b8cc12 from working; it's one thing for display, but actually storing sha1 as the thing being trusted is a different level of safety. I'm having trouble seeing "openssl has a bad default" as a reason to let users do things they shouldn't.

**Comment by vathpela** [comment]
FYI I've also got https://github.com/vathpela/mokutil/commit/8d5000f345e027b920929f32f36bd98cce5fcb48 in the RHEL mokutil package, so users don't do something that won't work.

**Pull request closed without merging**
